INSERT INTO Productos (nombre, descripcion, precio, categoria, imagen_url, stock) VALUES
('ROG Zephyrus G16 (2026) GU606', 'El Zephyrus G16 de 2026 y Windows 11 Pro hacen que jugar, crear contenido y todo lo demás sea pan comido. Equipado con un procesador Intel Core Ultra 9 386H y una GPU NVIDIA GeForce RTX 5090 para portátiles, este equipo de 16 pulgadas puede ejecutar sin problemas los últimos juegos y el software creativo más avanzado. El Zephyrus G16 puede transcribir notas de voz a documentos de texto sin esfuerzo, ahorrar tiempo valioso durante la renderización de vídeo y jugar a los últimos juegos AAA con una velocidad de actualización ultrarrápida. El futuro ya está aquí.', 65499.99, 'Computadoras', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/zephyrus.png', 5),
('iPhone 16 Pro Max', 'El último smartphone de Apple con chip A18 Pro y cámara de nivel profesional.', 25999.99, 'Smartphones', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/16_pro_max.jpg', 25),
('AirPods Pro', 'Auriculares inalámbricos con cancelación activa de ruido y audio espacial.', 4999.50, 'Audio', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/airpodsPro.png', 50),
('Logitech G502 X', 'Ratón inalámbrico gaming con interruptores óptico-mecánicos Lightforce.', 2599.90, 'Accesorios', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/g502x.png', 30),
('Redragon K552', 'Teclado mecánico gaming TKL compacto con interruptores mecánicos rápidos.', 999.99, 'Accesorios', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/k552.jpg', 40),
('Kit Focos Inteligentes', 'Kit de focos LED RGB inteligentes compatibles con Alexa y Google Assistant.', 799.50, 'Iluminación', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/kit_inteligentes.webp', 60),
('MacBook Pro 14"', 'Laptop profesional de Apple con chip M3, pantalla Liquid Retina XDR.', 34999.99, 'Computadoras', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/mac_14_pro.jpg', 15),
('Nanoleaf Shapes', 'Paneles de luz LED inteligentes modulares que reaccionan a la música.', 4299.99, 'Decoración', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/nanoleaft_shapes.webp', 20),
('Samsung Galaxy S26 Ultra', 'Teléfono de gama alta con S Pen integrado y cámaras con zoom espectacular.', 25999.50, 'Smartphones', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/s26_ultra.webp', 20),
('Tira LED 10m', 'Tira de luces LED RGB de 10 metros con control remoto y sincronización de música.', 499.99, 'Iluminación', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/tira_10cm.jpg', 75),
('Sony WH-1000XM5', 'Auriculares circumaurales inalámbricos líderes en cancelación de ruido.', 6999.90, 'Audio', 'https://e-commerce-e2.s3.us-east-1.amazonaws.com/wh_1000xm5.webp', 35);